services:
  - type: web
    name: ai-recruitment-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        value: recruitment_db
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 100
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: HF_MODEL
        value: mistralai/Mistral-7B-Instruct-v0.2
      - key: OLLAMA_MODEL
        value: mistral
      - key: USE_OLLAMA_AS_BACKUP
        value: true
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CORS_ORIGINS
        value: https://ai-recuitment-model.vercel.app
      - key: RATE_LIMIT_REQUESTS
        value: 100
      - key: RATE_LIMIT_PERIOD
        value: 60
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FILE
        value: app.log 